// words.js
// Each entry supplies the answer, a broad category, and a short clue.
const wordLibrary = [
  // Technology
  {word:"computer",category:"Technology",hint:"An electronic machine used to process information."},
  {word:"keyboard",category:"Technology",hint:"You type letters and commands with this."},
  {word:"smartphone",category:"Technology",hint:"A pocket device for calls, apps, and the internet."},
  {word:"internet",category:"Technology",hint:"The global network connecting devices."},
  {word:"browser",category:"Technology",hint:"An app used to visit websites."},
  {word:"server",category:"Technology",hint:"A computer that provides data or services to others."},
  {word:"database",category:"Technology",hint:"An organized collection of stored information."},
  {word:"software",category:"Technology",hint:"Programs and applications run by a device."},
  {word:"hardware",category:"Technology",hint:"The physical parts of a computer."},
  {word:"network",category:"Technology",hint:"Connected devices that can communicate."},
  {word:"password",category:"Technology",hint:"A secret phrase used to access an account."},
  {word:"encryption",category:"Technology",hint:"A way of protecting data by scrambling it."},
  {word:"algorithm",category:"Technology",hint:"A step-by-step method for solving a problem."},
  {word:"compiler",category:"Technology",hint:"Turns source code into another executable form."},
  {word:"terminal",category:"Technology",hint:"A text-based interface for running commands."},
  {word:"download",category:"Technology",hint:"Copying data from the internet to your device."},
  {word:"upload",category:"Technology",hint:"Sending a file from your device to another system."},
  {word:"application",category:"Technology",hint:"A program designed to perform a task."},
  {word:"interface",category:"Technology",hint:"The part of a system a user interacts with."},
  {word:"dashboard",category:"Technology",hint:"A screen showing important information at a glance."},
  {word:"cloud computing",category:"Technology",hint:"Using remote internet servers for computing tasks."},
  {word:"artificial intelligence",category:"Technology",hint:"Machines performing tasks associated with human intelligence."},
  {word:"machine learning",category:"Technology",hint:"Systems improving from examples and data."},
  {word:"virtual reality",category:"Technology",hint:"A computer-generated immersive environment."},
  {word:"augmented reality",category:"Technology",hint:"Digital content layered over the real world."},
  {word:"operating system",category:"Technology",hint:"Core software that manages a computer or phone."},
  {word:"search engine",category:"Technology",hint:"A service used to find information online."},
  {word:"web browser",category:"Technology",hint:"Software used to open and view web pages."},
  {word:"mobile phone",category:"Technology",hint:"A portable device used for calls and messaging."},
  {word:"cloud storage",category:"Technology",hint:"Files stored remotely and accessed online."},

  // Programming
  {word:"javascript",category:"Programming",hint:"A language widely used for interactive web pages."},
  {word:"programming",category:"Programming",hint:"Writing instructions for computers."},
  {word:"developer",category:"Programming",hint:"A person who builds software."},
  {word:"function",category:"Programming",hint:"A reusable block of code that performs a task."},
  {word:"variable",category:"Programming",hint:"A named place used to store a value."},
  {word:"parameter",category:"Programming",hint:"A value definition received by a function."},
  {word:"argument",category:"Programming",hint:"A value passed into a function call."},
  {word:"framework",category:"Programming",hint:"A reusable structure for building software."},
  {word:"repository",category:"Programming",hint:"A place where source code is stored and tracked."},
  {word:"breakpoint",category:"Programming",hint:"A marker that pauses code during debugging."},
  {word:"iteration",category:"Programming",hint:"One pass through a repeated process."},
  {word:"validation",category:"Programming",hint:"Checking whether data follows expected rules."},
  {word:"execution",category:"Programming",hint:"The act of running program instructions."},
  {word:"deployment",category:"Programming",hint:"Releasing software so people can use it."},
  {word:"migration",category:"Programming",hint:"Moving data or systems from one setup to another."},
  {word:"source code",category:"Programming",hint:"Human-readable instructions written by programmers."},
  {word:"open source",category:"Programming",hint:"Software whose code can be publicly inspected or changed."},
  {word:"full stack",category:"Programming",hint:"Working across both front-end and back-end development."},
  {word:"front end",category:"Programming",hint:"The user-facing part of a web application."},
  {word:"back end",category:"Programming",hint:"The server-side logic and data layer."},
  {word:"version control",category:"Programming",hint:"A system for tracking changes to files over time."},
  {word:"pull request",category:"Programming",hint:"A proposal to merge code changes into a project."},
  {word:"code review",category:"Programming",hint:"Checking another programmer's changes before merging."},
  {word:"unit test",category:"Programming",hint:"A small test focused on one piece of code."},
  {word:"event listener",category:"Programming",hint:"Code that waits for an action such as a click."},
  {word:"arrow function",category:"Programming",hint:"A concise JavaScript function syntax using an arrow."},
  {word:"command line",category:"Programming",hint:"A text interface where commands are typed."},
  {word:"local storage",category:"Programming",hint:"Browser storage that persists key-value data."},
  {word:"media query",category:"Programming",hint:"CSS rule used to adapt layouts to screen conditions."},
  {word:"grid layout",category:"Programming",hint:"A CSS system arranging items into rows and columns."},

  // Nature
  {word:"rainforest",category:"Nature",hint:"A dense forest with heavy rainfall."},
  {word:"mountain",category:"Nature",hint:"A very high natural rise in the land."},
  {word:"waterfall",category:"Nature",hint:"Water dropping over a steep edge."},
  {word:"volcano",category:"Nature",hint:"A mountain that can erupt lava and ash."},
  {word:"glacier",category:"Nature",hint:"A huge, slowly moving body of ice."},
  {word:"desert",category:"Nature",hint:"A very dry region with little rainfall."},
  {word:"ocean",category:"Nature",hint:"A vast body of salt water."},
  {word:"island",category:"Nature",hint:"Land completely surrounded by water."},
  {word:"river",category:"Nature",hint:"A natural flowing body of fresh water."},
  {word:"thunder",category:"Nature",hint:"The sound produced by lightning."},
  {word:"lightning",category:"Nature",hint:"A sudden electrical flash in the atmosphere."},
  {word:"hurricane",category:"Nature",hint:"A powerful rotating tropical storm."},
  {word:"tornado",category:"Nature",hint:"A violently rotating column of air."},
  {word:"earthquake",category:"Nature",hint:"Sudden shaking caused by movement in the Earth's crust."},
  {word:"coral reef",category:"Nature",hint:"An underwater ecosystem built by tiny marine animals."},
  {word:"northern lights",category:"Nature",hint:"Colorful sky glow seen near polar regions."},
  {word:"solar eclipse",category:"Nature",hint:"When the Moon blocks the Sun from view."},
  {word:"meteor shower",category:"Nature",hint:"Many streaks of light caused by space debris."},
  {word:"tropical storm",category:"Nature",hint:"A rotating low-pressure weather system over warm seas."},
  {word:"forest fire",category:"Nature",hint:"An uncontrolled fire spreading through woodland."},

  // Animals
  {word:"elephant",category:"Animals",hint:"The largest living land animal."},
  {word:"giraffe",category:"Animals",hint:"A very tall African animal with a long neck."},
  {word:"penguin",category:"Animals",hint:"A flightless bird adapted for swimming."},
  {word:"dolphin",category:"Animals",hint:"An intelligent marine mammal known for leaping."},
  {word:"kangaroo",category:"Animals",hint:"An Australian marsupial that moves by hopping."},
  {word:"crocodile",category:"Animals",hint:"A large reptile with powerful jaws."},
  {word:"octopus",category:"Animals",hint:"A sea animal with eight arms."},
  {word:"cheetah",category:"Animals",hint:"The fastest land animal."},
  {word:"gorilla",category:"Animals",hint:"A large and powerful great ape."},
  {word:"butterfly",category:"Animals",hint:"An insect with colorful wings."},
  {word:"dragonfly",category:"Animals",hint:"A fast-flying insect often found near water."},
  {word:"seahorse",category:"Animals",hint:"A small marine fish with a horse-shaped head."},
  {word:"polar bear",category:"Animals",hint:"A large white bear from the Arctic."},
  {word:"sea turtle",category:"Animals",hint:"A marine reptile protected by a shell."},
  {word:"snow leopard",category:"Animals",hint:"A pale big cat living in high Asian mountains."},
  {word:"giant panda",category:"Animals",hint:"A black-and-white bear that eats mostly bamboo."},
  {word:"golden eagle",category:"Animals",hint:"A large bird of prey with powerful eyesight."},
  {word:"blue whale",category:"Animals",hint:"The largest animal known to have lived."},
  {word:"red fox",category:"Animals",hint:"A clever reddish wild canine."},
  {word:"honey bee",category:"Animals",hint:"An insect that makes honey and pollinates flowers."},

  // Food
  {word:"chocolate",category:"Food",hint:"A sweet made from cacao."},
  {word:"pineapple",category:"Food",hint:"A tropical fruit with a rough spiky skin."},
  {word:"strawberry",category:"Food",hint:"A small red fruit with seeds on the outside."},
  {word:"watermelon",category:"Food",hint:"A large fruit with green skin and juicy red flesh."},
  {word:"spaghetti",category:"Food",hint:"Long thin strands of Italian pasta."},
  {word:"sandwich",category:"Food",hint:"Food placed between slices of bread."},
  {word:"pancake",category:"Food",hint:"A flat round cake cooked in a pan."},
  {word:"popcorn",category:"Food",hint:"A snack made from heated corn kernels."},
  {word:"cheesecake",category:"Food",hint:"A rich dessert made with soft cheese."},
  {word:"croissant",category:"Food",hint:"A flaky crescent-shaped pastry."},
  {word:"fried rice",category:"Food",hint:"Rice stir-fried with other ingredients."},
  {word:"ice cream",category:"Food",hint:"A sweet frozen dessert."},
  {word:"apple pie",category:"Food",hint:"A baked dessert filled with sliced apples."},
  {word:"hot chocolate",category:"Food",hint:"A warm drink made with cocoa."},
  {word:"peanut butter",category:"Food",hint:"A spread made from ground roasted peanuts."},
  {word:"chicken soup",category:"Food",hint:"A warm broth-based dish made with poultry."},
  {word:"french fries",category:"Food",hint:"Thin strips of potato cooked in hot oil."},
  {word:"orange juice",category:"Food",hint:"A drink squeezed from citrus fruit."},
  {word:"birthday cake",category:"Food",hint:"A celebratory dessert usually topped with candles."},
  {word:"tomato sauce",category:"Food",hint:"A red sauce commonly used with pasta or pizza."},

  // Places & Travel
  {word:"airport",category:"Travel",hint:"Where passenger aircraft arrive and depart."},
  {word:"passport",category:"Travel",hint:"An official document used for international travel."},
  {word:"suitcase",category:"Travel",hint:"A case used to carry clothes while traveling."},
  {word:"backpack",category:"Travel",hint:"A bag carried on your back."},
  {word:"hotel",category:"Travel",hint:"A place where travelers pay to stay overnight."},
  {word:"museum",category:"Places",hint:"A building where historical, scientific, or artistic objects are displayed."},
  {word:"library",category:"Places",hint:"A place where books can be read or borrowed."},
  {word:"stadium",category:"Places",hint:"A large venue used for sports and events."},
  {word:"hospital",category:"Places",hint:"A place where sick or injured people receive medical care."},
  {word:"university",category:"Places",hint:"An institution for higher education."},
  {word:"train station",category:"Travel",hint:"A place where rail passengers board and leave trains."},
  {word:"boarding pass",category:"Travel",hint:"A document allowing a passenger onto a flight."},
  {word:"road trip",category:"Travel",hint:"A long journey made by car."},
  {word:"travel guide",category:"Travel",hint:"A resource offering information about destinations."},
  {word:"city center",category:"Places",hint:"The central commercial area of a city."},
  {word:"national park",category:"Places",hint:"Protected land preserved for nature and visitors."},
  {word:"theme park",category:"Places",hint:"An attraction filled with rides and entertainment."},
  {word:"shopping mall",category:"Places",hint:"A large indoor complex containing many stores."},
  {word:"coffee shop",category:"Places",hint:"A cafe specializing in coffee and light food."},
  {word:"bus terminal",category:"Travel",hint:"A station where bus routes begin or end."},

  // Sports
  {word:"football",category:"Sports",hint:"A team game played with a ball and goals."},
  {word:"basketball",category:"Sports",hint:"A game where players shoot a ball through a hoop."},
  {word:"badminton",category:"Sports",hint:"A racket sport played with a shuttlecock."},
  {word:"swimming",category:"Sports",hint:"Moving through water using the arms and legs."},
  {word:"baseball",category:"Sports",hint:"A bat-and-ball game played on a diamond."},
  {word:"volleyball",category:"Sports",hint:"Teams hit a ball over a high net."},
  {word:"marathon",category:"Sports",hint:"A long-distance running race of about 42 kilometers."},
  {word:"cycling",category:"Sports",hint:"Riding a bicycle as sport or exercise."},
  {word:"gymnastics",category:"Sports",hint:"A sport involving strength, balance, and acrobatic movement."},
  {word:"skateboard",category:"Sports",hint:"A wheeled board used for riding and tricks."},
  {word:"table tennis",category:"Sports",hint:"A small racket sport played across a table."},
  {word:"martial arts",category:"Sports",hint:"Systems of combat practiced for sport or self-defense."},
  {word:"world cup",category:"Sports",hint:"A major international tournament title used by several sports."},
  {word:"finish line",category:"Sports",hint:"The point that marks the end of a race."},
  {word:"gold medal",category:"Sports",hint:"The prize commonly awarded for first place."},
  {word:"penalty kick",category:"Sports",hint:"A direct shot awarded after certain football fouls."},
  {word:"tennis court",category:"Sports",hint:"The marked surface where tennis is played."},
  {word:"boxing ring",category:"Sports",hint:"The square area where boxing matches take place."},
  {word:"race track",category:"Sports",hint:"A course designed for racing."},
  {word:"team captain",category:"Sports",hint:"The player chosen to lead a team."},

  // Science
  {word:"gravity",category:"Science",hint:"The force that attracts objects with mass."},
  {word:"oxygen",category:"Science",hint:"A gas essential for human respiration."},
  {word:"hydrogen",category:"Science",hint:"The lightest chemical element."},
  {word:"molecule",category:"Science",hint:"Two or more atoms chemically bonded together."},
  {word:"electron",category:"Science",hint:"A negatively charged subatomic particle."},
  {word:"telescope",category:"Science",hint:"An instrument used to view distant objects in space."},
  {word:"microscope",category:"Science",hint:"An instrument used to view very small objects."},
  {word:"laboratory",category:"Science",hint:"A place equipped for scientific experiments."},
  {word:"satellite",category:"Science",hint:"An object orbiting a planet or other body."},
  {word:"astronaut",category:"Science",hint:"A person trained to travel in space."},
  {word:"solar system",category:"Science",hint:"The Sun and all objects gravitationally bound to it."},
  {word:"black hole",category:"Science",hint:"A region where gravity is so strong that light cannot escape."},
  {word:"periodic table",category:"Science",hint:"A chart organizing the chemical elements."},
  {word:"speed of light",category:"Science",hint:"The maximum speed at which light travels in a vacuum."},
  {word:"human brain",category:"Science",hint:"The organ responsible for thought and nervous control."},
  {word:"blood vessel",category:"Science",hint:"A tube that carries blood through the body."},
  {word:"food chain",category:"Science",hint:"A sequence showing how energy passes between organisms."},
  {word:"climate change",category:"Science",hint:"Long-term shifts in Earth's temperature and weather patterns."},
  {word:"renewable energy",category:"Science",hint:"Power from naturally replenished sources."},
  {word:"carbon dioxide",category:"Science",hint:"A gas containing one carbon and two oxygen atoms."},

  // Everyday Life
  {word:"umbrella",category:"Everyday Life",hint:"A portable cover used to keep off rain."},
  {word:"toothbrush",category:"Everyday Life",hint:"A tool used to clean teeth."},
  {word:"refrigerator",category:"Everyday Life",hint:"An appliance that keeps food cold."},
  {word:"microwave",category:"Everyday Life",hint:"A kitchen appliance that heats food quickly."},
  {word:"calendar",category:"Everyday Life",hint:"A system showing days, weeks, and months."},
  {word:"notebook",category:"Everyday Life",hint:"A bound set of blank pages for writing."},
  {word:"headphones",category:"Everyday Life",hint:"Audio speakers worn over or in the ears."},
  {word:"flashlight",category:"Everyday Life",hint:"A portable battery-powered light."},
  {word:"doorbell",category:"Everyday Life",hint:"A device visitors use to signal at a door."},
  {word:"wallet",category:"Everyday Life",hint:"A small holder for money and cards."},
  {word:"alarm clock",category:"Everyday Life",hint:"A clock designed to wake you at a chosen time."},
  {word:"washing machine",category:"Everyday Life",hint:"An appliance used to clean clothes."},
  {word:"dining table",category:"Everyday Life",hint:"Furniture where people sit to eat."},
  {word:"coffee mug",category:"Everyday Life",hint:"A handled cup commonly used for hot drinks."},
  {word:"light switch",category:"Everyday Life",hint:"A control used to turn a light on or off."},
  {word:"shopping cart",category:"Everyday Life",hint:"A wheeled basket used to carry goods in a store."},
  {word:"phone charger",category:"Everyday Life",hint:"A device that restores power to a phone battery."},
  {word:"remote control",category:"Everyday Life",hint:"A handheld device for operating equipment from a distance."},
  {word:"water bottle",category:"Everyday Life",hint:"A portable container used for drinking water."},
  {word:"office chair",category:"Everyday Life",hint:"A chair designed for desk work."},

  // Entertainment
  {word:"cinema",category:"Entertainment",hint:"A place where films are shown to an audience."},
  {word:"cartoon",category:"Entertainment",hint:"An animated or illustrated form of entertainment."},
  {word:"podcast",category:"Entertainment",hint:"An episodic audio program available online."},
  {word:"concert",category:"Entertainment",hint:"A live musical performance."},
  {word:"playlist",category:"Entertainment",hint:"A chosen sequence of songs or audio tracks."},
  {word:"photography",category:"Entertainment",hint:"The art of creating images with a camera."},
  {word:"video game",category:"Entertainment",hint:"An interactive electronic game played on a screen."},
  {word:"board game",category:"Entertainment",hint:"A tabletop game played using a board and pieces."},
  {word:"comic book",category:"Entertainment",hint:"A publication that tells stories using sequential art."},
  {word:"movie theater",category:"Entertainment",hint:"Another term for a cinema."},
  {word:"music festival",category:"Entertainment",hint:"An event featuring many live musical performances."},
  {word:"television show",category:"Entertainment",hint:"A program broadcast or streamed in episodes."},
  {word:"action movie",category:"Entertainment",hint:"A film genre focused on fights, chases, and excitement."},
  {word:"science fiction",category:"Entertainment",hint:"Stories based on imagined science or future technology."},
  {word:"mystery novel",category:"Entertainment",hint:"A book centered on solving a puzzle or crime."},
  {word:"live stream",category:"Entertainment",hint:"Video or audio broadcast over the internet in real time."},
  {word:"game controller",category:"Entertainment",hint:"A handheld input device used to play games."},
  {word:"movie ticket",category:"Entertainment",hint:"A pass that admits someone to a film screening."},
  {word:"camera lens",category:"Entertainment",hint:"The optical part of a camera that focuses light."},
  {word:"sound effect",category:"Entertainment",hint:"An artificially created or enhanced sound used in media."}
];